content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, published ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
